In [2]:
# 1. 헬스장 데이터 가져오기

In [128]:
import pandas as pd

data = pd.read_csv('서울시 체력단련장업 인허가 정보.csv', encoding='cp949')     # csv 파일 읽기
data.head()            # 상위 5개 확인

,개방자치단체코드,관리번호,인허가일자,인허가취소일자,영업상태코드,영업상태명,상세영업상태코드,상세영업상태명,폐업일자,휴업시작일자,...,좌표정보(Y),문화체육업종명,공사립구분명,보험가입여부코드,지도자수,건축물동수,건축물연면적,회원모집총인원,세부업종명,법인명
0,3030000,CDFH3301061993000002,19930701,NaN,3,폐업,3,폐업,20040417.0,NaN,...,NaN,체력단련장업,사립,0,NaN,NaN,NaN,NaN,NaN,NaN
1,3030000,CDFH3301061994000001,19940127,NaN,3,폐업,3,폐업,20011106.0,NaN,...,449353.789642,체력단련장업,사립,NaN,0.0,0.0,0.0,NaN,NaN,NaN
2,3180000,CDFH3301062004000008,20040729,NaN,3,폐업,3,폐업,20220421.0,NaN,...,446698.814323,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3060000,CDFH3301062022000006,20220516,NaN,1,영업/정상,13,영업중,NaN,NaN,...,456686.933364,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3160000,CDFH3301062020000001,20200131,NaN,1,영업/정상,13,영업중,NaN,NaN,...,443955.614465,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [129]:
data.tail()          # 하위 5개 확인

,개방자치단체코드,관리번호,인허가일자,인허가취소일자,영업상태코드,영업상태명,상세영업상태코드,상세영업상태명,폐업일자,휴업시작일자,...,좌표정보(Y),문화체육업종명,공사립구분명,보험가입여부코드,지도자수,건축물동수,건축물연면적,회원모집총인원,세부업종명,법인명
5472,3180000,CDFH3301062022000025,20221020,NaN,1,영업/정상,13,영업중,NaN,NaN,...,448230.132883,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5473,3230000,CDFH3301062019000010,20190625,NaN,1,영업/정상,13,영업중,NaN,NaN,...,442139.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5474,3220000,CDFH3301062022000049,20221021,NaN,1,영업/정상,13,영업중,NaN,NaN,...,445698.726213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5475,3200000,CDFH3301062022000025,20221027,NaN,1,영업/정상,13,영업중,NaN,NaN,...,442694.768284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5476,3230000,CDFH3301062022000025,20221018,NaN,3,폐업,3,폐업,20221031.0,NaN,...,446040.044745,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [130]:
data.columns

Index(['개방자치단체코드', '관리번호', '인허가일자', '인허가취소일자', '영업상태코드', '영업상태명', '상세영업상태코드',
       '상세영업상태명', '폐업일자', '휴업시작일자', '휴업종료일자', '재개업일자', '전화번호', '소재지면적',
       '소재지우편번호', '지번주소', '도로명주소', '도로명우편번호', '사업장명', '최종수정일자', '데이터갱신구분',
       '데이터갱신일자', '업태구분명', '좌표정보(X)', '좌표정보(Y)', '문화체육업종명', '공사립구분명',
       '보험가입여부코드', '지도자수', '건축물동수', '건축물연면적', '회원모집총인원', '세부업종명', '법인명'],
      dtype='object')

In [131]:
df = pd.DataFrame(data)
df = df[[ '사업장명','상세영업상태명','지번주소','도로명주소']]
df

,사업장명,상세영업상태명,지번주소,도로명주소
0,신화헬스클럽,폐업,서울특별시 성동구 홍익동 162-1번지,NaN
1,성수헬스,폐업,서울특별시 성동구 성수동2가 289-243번지,서울특별시 성동구 아차산로7길 14-1 (성수동2가)
2,유통헬스,폐업,서울특별시 영등포구 당산동2가 30-2,서울특별시 영등포구 영등포로 109 (당산동2가 영등포유통상가)
3,J-PT,영업중,서울특별시 중랑구 묵동 174-29,서울특별시 중랑구 공릉로 18 3층 (묵동)
4,메이크유 필라테스&PT,영업중,서울특별시 구로구 고척동 76-160 골든타워빌딩 4층,서울특별시 구로구 경인로 397 골든타워빌딩 4층 (고척동)
...,...,...,...,...
5472,크로스핏 긱스,영업중,서울특별시 영등포구 당산동6가 347-6 지하1층,서울특별시 영등포구 양평로12가길 4 지하1층 (당산동6가)
5473,짐구석,영업중,서울특별시 송파구 장지동 881-5 에스비트램스퀘어,서울특별시 송파구 위례광장로 200 에스비트램스퀘어 10층 (장지동)
5474,와이짐(Y GYM),영업중,서울특별시 강남구 논현동 42-7,서울특별시 강남구 강남대로132길 59 2층 (논현동)
5475,운동해야짐,영업중,서울특별시 관악구 봉천동 463-3,서울특별시 관악구 양녕로 50 3층 (봉천동)
5476,피지오원,폐업,서울특별시 송파구 방이동 45-2 805호,서울특별시 송파구 위례성대로 18 805호 (방이동)

In [132]:
# 영업중인 매장 sorting
df = df[df['상세영업상태명']=='영업중']
df

,사업장명,상세영업상태명,지번주소,도로명주소
3,J-PT,영업중,서울특별시 중랑구 묵동 174-29,서울특별시 중랑구 공릉로 18 3층 (묵동)
4,메이크유 필라테스&PT,영업중,서울특별시 구로구 고척동 76-160 골든타워빌딩 4층,서울특별시 구로구 경인로 397 골든타워빌딩 4층 (고척동)
6,에스짐 양천구청점,영업중,서울특별시 양천구 신정동 294-44,서울특별시 양천구 목동동로8길 15 34층 (신정동)
7,테디짐PT 서초래미안,영업중,서울특별시 서초구 서초동 1682 서초래미안아파트,서울특별시 서초구 서초대로65길 13-10 2층 207호 (서초동 서초래미안아파트)
9,플레이스짐,영업중,서울특별시 은평구 역촌동 16-19 니오빌딩,서울특별시 은평구 진흥로 105-6 니오빌딩 2층 (역촌동)
...,...,...,...,...
5471,크로스핏 쿠타짐 영등포,영업중,서울특별시 영등포구 양평동3가 77-53 케이타워 지하1층,서울특별시 영등포구 선유동2로 9 케이타워 지하1층 (양평동3가)
5472,크로스핏 긱스,영업중,서울특별시 영등포구 당산동6가 347-6 지하1층,서울특별시 영등포구 양평로12가길 4 지하1층 (당산동6가)
5473,짐구석,영업중,서울특별시 송파구 장지동 881-5 에스비트램스퀘어,서울특별시 송파구 위례광장로 200 에스비트램스퀘어 10층 (장지동)
5474,와이짐(Y GYM),영업중,서울특별시 강남구 논현동 42-7,서울특별시 강남구 강남대로132길 59 2층 (논현동)
5475,운동해야짐,영업중,서울특별시 관악구 봉천동 463-3,서울특별시 관악구 양녕로 50 3층 (봉천동)

In [133]:
# 인덱스 재정렬
df = df.reset_index(drop=True)
df

,사업장명,상세영업상태명,지번주소,도로명주소
0,J-PT,영업중,서울특별시 중랑구 묵동 174-29,서울특별시 중랑구 공릉로 18 3층 (묵동)
1,메이크유 필라테스&PT,영업중,서울특별시 구로구 고척동 76-160 골든타워빌딩 4층,서울특별시 구로구 경인로 397 골든타워빌딩 4층 (고척동)
2,에스짐 양천구청점,영업중,서울특별시 양천구 신정동 294-44,서울특별시 양천구 목동동로8길 15 34층 (신정동)
3,테디짐PT 서초래미안,영업중,서울특별시 서초구 서초동 1682 서초래미안아파트,서울특별시 서초구 서초대로65길 13-10 2층 207호 (서초동 서초래미안아파트)
4,플레이스짐,영업중,서울특별시 은평구 역촌동 16-19 니오빌딩,서울특별시 은평구 진흥로 105-6 니오빌딩 2층 (역촌동)
...,...,...,...,...
3306,크로스핏 쿠타짐 영등포,영업중,서울특별시 영등포구 양평동3가 77-53 케이타워 지하1층,서울특별시 영등포구 선유동2로 9 케이타워 지하1층 (양평동3가)
3307,크로스핏 긱스,영업중,서울특별시 영등포구 당산동6가 347-6 지하1층,서울특별시 영등포구 양평로12가길 4 지하1층 (당산동6가)
3308,짐구석,영업중,서울특별시 송파구 장지동 881-5 에스비트램스퀘어,서울특별시 송파구 위례광장로 200 에스비트램스퀘어 10층 (장지동)
3309,와이짐(Y GYM),영업중,서울특별시 강남구 논현동 42-7,서울특별시 강남구 강남대로132길 59 2층 (논현동)
3310,운동해야짐,영업중,서울특별시 관악구 봉천동 463-3,서울특별시 관악구 양녕로 50 3층 (봉천동)

In [134]:
# 지번 주소에서 구 parsing
address_split = df["지번주소"].str.split(" ")
df["지번(구)"] = address_split.str.get(1)
df

,사업장명,상세영업상태명,지번주소,도로명주소,지번(구)
0,J-PT,영업중,서울특별시 중랑구 묵동 174-29,서울특별시 중랑구 공릉로 18 3층 (묵동),중랑구
1,메이크유 필라테스&PT,영업중,서울특별시 구로구 고척동 76-160 골든타워빌딩 4층,서울특별시 구로구 경인로 397 골든타워빌딩 4층 (고척동),구로구
2,에스짐 양천구청점,영업중,서울특별시 양천구 신정동 294-44,서울특별시 양천구 목동동로8길 15 34층 (신정동),양천구
3,테디짐PT 서초래미안,영업중,서울특별시 서초구 서초동 1682 서초래미안아파트,서울특별시 서초구 서초대로65길 13-10 2층 207호 (서초동 서초래미안아파트),서초구
4,플레이스짐,영업중,서울특별시 은평구 역촌동 16-19 니오빌딩,서울특별시 은평구 진흥로 105-6 니오빌딩 2층 (역촌동),은평구
...,...,...,...,...,...
3306,크로스핏 쿠타짐 영등포,영업중,서울특별시 영등포구 양평동3가 77-53 케이타워 지하1층,서울특별시 영등포구 선유동2로 9 케이타워 지하1층 (양평동3가),영등포구
3307,크로스핏 긱스,영업중,서울특별시 영등포구 당산동6가 347-6 지하1층,서울특별시 영등포구 양평로12가길 4 지하1층 (당산동6가),영등포구
3308,짐구석,영업중,서울특별시 송파구 장지동 881-5 에스비트램스퀘어,서울특별시 송파구 위례광장로 200 에스비트램스퀘어 10층 (장지동),송파구
3309,와이짐(Y GYM),영업중,서울특별시 강남구 논현동 42-7,서울특별시 강남구 강남대로132길 59 2층 (논현동),강남구
3310,운동해야짐,영업중,서울특별시 관악구 봉천동 463-3,서울특별시 관악구 양녕로 50 3층 (봉천동),관악구

In [135]:
# 도로명 주소에서 구 parsing
address_split = df["도로명주소"].str.split(" ")
df["도로명(구)"] = address_split.str.get(1)
df

,사업장명,상세영업상태명,지번주소,도로명주소,지번(구),도로명(구)
0,J-PT,영업중,서울특별시 중랑구 묵동 174-29,서울특별시 중랑구 공릉로 18 3층 (묵동),중랑구,중랑구
1,메이크유 필라테스&PT,영업중,서울특별시 구로구 고척동 76-160 골든타워빌딩 4층,서울특별시 구로구 경인로 397 골든타워빌딩 4층 (고척동),구로구,구로구
2,에스짐 양천구청점,영업중,서울특별시 양천구 신정동 294-44,서울특별시 양천구 목동동로8길 15 34층 (신정동),양천구,양천구
3,테디짐PT 서초래미안,영업중,서울특별시 서초구 서초동 1682 서초래미안아파트,서울특별시 서초구 서초대로65길 13-10 2층 207호 (서초동 서초래미안아파트),서초구,서초구
4,플레이스짐,영업중,서울특별시 은평구 역촌동 16-19 니오빌딩,서울특별시 은평구 진흥로 105-6 니오빌딩 2층 (역촌동),은평구,은평구
...,...,...,...,...,...,...
3306,크로스핏 쿠타짐 영등포,영업중,서울특별시 영등포구 양평동3가 77-53 케이타워 지하1층,서울특별시 영등포구 선유동2로 9 케이타워 지하1층 (양평동3가),영등포구,영등포구
3307,크로스핏 긱스,영업중,서울특별시 영등포구 당산동6가 347-6 지하1층,서울특별시 영등포구 양평로12가길 4 지하1층 (당산동6가),영등포구,영등포구
3308,짐구석,영업중,서울특별시 송파구 장지동 881-5 에스비트램스퀘어,서울특별시 송파구 위례광장로 200 에스비트램스퀘어 10층 (장지동),송파구,송파구
3309,와이짐(Y GYM),영업중,서울특별시 강남구 논현동 42-7,서울특별시 강남구 강남대로132길 59 2층 (논현동),강남구,강남구
3310,운동해야짐,영업중,서울특별시 관악구 봉천동 463-3,서울특별시 관악구 양녕로 50 3층 (봉천동),관악구,관악구