In [2]:
# 1. 헬스장 데이터 가져오기

In [97]:
import pandas as pd

data = pd.read_csv('서울시 체력단련장업 인허가 정보.csv', encoding='cp949')     # csv 파일 읽기
data.head()            # 상위 5개 확인

,개방자치단체코드,관리번호,인허가일자,인허가취소일자,영업상태코드,영업상태명,상세영업상태코드,상세영업상태명,폐업일자,휴업시작일자,...,좌표정보(Y),문화체육업종명,공사립구분명,보험가입여부코드,지도자수,건축물동수,건축물연면적,회원모집총인원,세부업종명,법인명
0,3030000,CDFH3301061993000002,19930701,NaN,3,폐업,3,폐업,20040417.0,NaN,...,NaN,체력단련장업,사립,0,NaN,NaN,NaN,NaN,NaN,NaN
1,3030000,CDFH3301061994000001,19940127,NaN,3,폐업,3,폐업,20011106.0,NaN,...,449353.789642,체력단련장업,사립,NaN,0.0,0.0,0.0,NaN,NaN,NaN
2,3180000,CDFH3301062004000008,20040729,NaN,3,폐업,3,폐업,20220421.0,NaN,...,446698.814323,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3060000,CDFH3301062022000006,20220516,NaN,1,영업/정상,13,영업중,NaN,NaN,...,456686.933364,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3160000,CDFH3301062020000001,20200131,NaN,1,영업/정상,13,영업중,NaN,NaN,...,443955.614465,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [98]:
data.tail()          # 하위 5개 확인

,개방자치단체코드,관리번호,인허가일자,인허가취소일자,영업상태코드,영업상태명,상세영업상태코드,상세영업상태명,폐업일자,휴업시작일자,...,좌표정보(Y),문화체육업종명,공사립구분명,보험가입여부코드,지도자수,건축물동수,건축물연면적,회원모집총인원,세부업종명,법인명
5472,3180000,CDFH3301062022000025,20221020,NaN,1,영업/정상,13,영업중,NaN,NaN,...,448230.132883,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5473,3230000,CDFH3301062019000010,20190625,NaN,1,영업/정상,13,영업중,NaN,NaN,...,442139.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5474,3220000,CDFH3301062022000049,20221021,NaN,1,영업/정상,13,영업중,NaN,NaN,...,445698.726213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5475,3200000,CDFH3301062022000025,20221027,NaN,1,영업/정상,13,영업중,NaN,NaN,...,442694.768284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5476,3230000,CDFH3301062022000025,20221018,NaN,3,폐업,3,폐업,20221031.0,NaN,...,446040.044745,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [99]:
# 전체 구분 목록 가져오기
data.columns

Index(['개방자치단체코드', '관리번호', '인허가일자', '인허가취소일자', '영업상태코드', '영업상태명', '상세영업상태코드',
       '상세영업상태명', '폐업일자', '휴업시작일자', '휴업종료일자', '재개업일자', '전화번호', '소재지면적',
       '소재지우편번호', '지번주소', '도로명주소', '도로명우편번호', '사업장명', '최종수정일자', '데이터갱신구분',
       '데이터갱신일자', '업태구분명', '좌표정보(X)', '좌표정보(Y)', '문화체육업종명', '공사립구분명',
       '보험가입여부코드', '지도자수', '건축물동수', '건축물연면적', '회원모집총인원', '세부업종명', '법인명'],
      dtype='object')

In [100]:
# 필요한 열 추출
# 전체 매장 5477개
df = pd.DataFrame(data)
df = df[[ '사업장명','상세영업상태명','지번주소','도로명주소']]
df

,사업장명,상세영업상태명,지번주소,도로명주소
0,신화헬스클럽,폐업,서울특별시 성동구 홍익동 162-1번지,NaN
1,성수헬스,폐업,서울특별시 성동구 성수동2가 289-243번지,서울특별시 성동구 아차산로7길 14-1 (성수동2가)
2,유통헬스,폐업,서울특별시 영등포구 당산동2가 30-2,서울특별시 영등포구 영등포로 109 (당산동2가 영등포유통상가)
3,J-PT,영업중,서울특별시 중랑구 묵동 174-29,서울특별시 중랑구 공릉로 18 3층 (묵동)
4,메이크유 필라테스&PT,영업중,서울특별시 구로구 고척동 76-160 골든타워빌딩 4층,서울특별시 구로구 경인로 397 골든타워빌딩 4층 (고척동)
...,...,...,...,...
5472,크로스핏 긱스,영업중,서울특별시 영등포구 당산동6가 347-6 지하1층,서울특별시 영등포구 양평로12가길 4 지하1층 (당산동6가)
5473,짐구석,영업중,서울특별시 송파구 장지동 881-5 에스비트램스퀘어,서울특별시 송파구 위례광장로 200 에스비트램스퀘어 10층 (장지동)
5474,와이짐(Y GYM),영업중,서울특별시 강남구 논현동 42-7,서울특별시 강남구 강남대로132길 59 2층 (논현동)
5475,운동해야짐,영업중,서울특별시 관악구 봉천동 463-3,서울특별시 관악구 양녕로 50 3층 (봉천동)
5476,피지오원,폐업,서울특별시 송파구 방이동 45-2 805호,서울특별시 송파구 위례성대로 18 805호 (방이동)

In [101]:
# 영업중인 매장 sorting, 총 3311개
df = df[df['상세영업상태명']=='영업중']
df

,사업장명,상세영업상태명,지번주소,도로명주소
3,J-PT,영업중,서울특별시 중랑구 묵동 174-29,서울특별시 중랑구 공릉로 18 3층 (묵동)
4,메이크유 필라테스&PT,영업중,서울특별시 구로구 고척동 76-160 골든타워빌딩 4층,서울특별시 구로구 경인로 397 골든타워빌딩 4층 (고척동)
6,에스짐 양천구청점,영업중,서울특별시 양천구 신정동 294-44,서울특별시 양천구 목동동로8길 15 34층 (신정동)
7,테디짐PT 서초래미안,영업중,서울특별시 서초구 서초동 1682 서초래미안아파트,서울특별시 서초구 서초대로65길 13-10 2층 207호 (서초동 서초래미안아파트)
9,플레이스짐,영업중,서울특별시 은평구 역촌동 16-19 니오빌딩,서울특별시 은평구 진흥로 105-6 니오빌딩 2층 (역촌동)
...,...,...,...,...
5471,크로스핏 쿠타짐 영등포,영업중,서울특별시 영등포구 양평동3가 77-53 케이타워 지하1층,서울특별시 영등포구 선유동2로 9 케이타워 지하1층 (양평동3가)
5472,크로스핏 긱스,영업중,서울특별시 영등포구 당산동6가 347-6 지하1층,서울특별시 영등포구 양평로12가길 4 지하1층 (당산동6가)
5473,짐구석,영업중,서울특별시 송파구 장지동 881-5 에스비트램스퀘어,서울특별시 송파구 위례광장로 200 에스비트램스퀘어 10층 (장지동)
5474,와이짐(Y GYM),영업중,서울특별시 강남구 논현동 42-7,서울특별시 강남구 강남대로132길 59 2층 (논현동)
5475,운동해야짐,영업중,서울특별시 관악구 봉천동 463-3,서울특별시 관악구 양녕로 50 3층 (봉천동)

In [102]:
# 인덱스 재정렬
df = df.reset_index(drop=True)
df

,사업장명,상세영업상태명,지번주소,도로명주소
0,J-PT,영업중,서울특별시 중랑구 묵동 174-29,서울특별시 중랑구 공릉로 18 3층 (묵동)
1,메이크유 필라테스&PT,영업중,서울특별시 구로구 고척동 76-160 골든타워빌딩 4층,서울특별시 구로구 경인로 397 골든타워빌딩 4층 (고척동)
2,에스짐 양천구청점,영업중,서울특별시 양천구 신정동 294-44,서울특별시 양천구 목동동로8길 15 34층 (신정동)
3,테디짐PT 서초래미안,영업중,서울특별시 서초구 서초동 1682 서초래미안아파트,서울특별시 서초구 서초대로65길 13-10 2층 207호 (서초동 서초래미안아파트)
4,플레이스짐,영업중,서울특별시 은평구 역촌동 16-19 니오빌딩,서울특별시 은평구 진흥로 105-6 니오빌딩 2층 (역촌동)
...,...,...,...,...
3306,크로스핏 쿠타짐 영등포,영업중,서울특별시 영등포구 양평동3가 77-53 케이타워 지하1층,서울특별시 영등포구 선유동2로 9 케이타워 지하1층 (양평동3가)
3307,크로스핏 긱스,영업중,서울특별시 영등포구 당산동6가 347-6 지하1층,서울특별시 영등포구 양평로12가길 4 지하1층 (당산동6가)
3308,짐구석,영업중,서울특별시 송파구 장지동 881-5 에스비트램스퀘어,서울특별시 송파구 위례광장로 200 에스비트램스퀘어 10층 (장지동)
3309,와이짐(Y GYM),영업중,서울특별시 강남구 논현동 42-7,서울특별시 강남구 강남대로132길 59 2층 (논현동)
3310,운동해야짐,영업중,서울특별시 관악구 봉천동 463-3,서울특별시 관악구 양녕로 50 3층 (봉천동)

In [103]:
# 지번 주소에서 구 parsing
address_split = df["지번주소"].str.split(" ")
df["지번(구)"] = address_split.str.get(1)
df

,사업장명,상세영업상태명,지번주소,도로명주소,지번(구)
0,J-PT,영업중,서울특별시 중랑구 묵동 174-29,서울특별시 중랑구 공릉로 18 3층 (묵동),중랑구
1,메이크유 필라테스&PT,영업중,서울특별시 구로구 고척동 76-160 골든타워빌딩 4층,서울특별시 구로구 경인로 397 골든타워빌딩 4층 (고척동),구로구
2,에스짐 양천구청점,영업중,서울특별시 양천구 신정동 294-44,서울특별시 양천구 목동동로8길 15 34층 (신정동),양천구
3,테디짐PT 서초래미안,영업중,서울특별시 서초구 서초동 1682 서초래미안아파트,서울특별시 서초구 서초대로65길 13-10 2층 207호 (서초동 서초래미안아파트),서초구
4,플레이스짐,영업중,서울특별시 은평구 역촌동 16-19 니오빌딩,서울특별시 은평구 진흥로 105-6 니오빌딩 2층 (역촌동),은평구
...,...,...,...,...,...
3306,크로스핏 쿠타짐 영등포,영업중,서울특별시 영등포구 양평동3가 77-53 케이타워 지하1층,서울특별시 영등포구 선유동2로 9 케이타워 지하1층 (양평동3가),영등포구
3307,크로스핏 긱스,영업중,서울특별시 영등포구 당산동6가 347-6 지하1층,서울특별시 영등포구 양평로12가길 4 지하1층 (당산동6가),영등포구
3308,짐구석,영업중,서울특별시 송파구 장지동 881-5 에스비트램스퀘어,서울특별시 송파구 위례광장로 200 에스비트램스퀘어 10층 (장지동),송파구
3309,와이짐(Y GYM),영업중,서울특별시 강남구 논현동 42-7,서울특별시 강남구 강남대로132길 59 2층 (논현동),강남구
3310,운동해야짐,영업중,서울특별시 관악구 봉천동 463-3,서울특별시 관악구 양녕로 50 3층 (봉천동),관악구

In [104]:
# 도로명 주소에서 구 parsing
address_split = df["도로명주소"].str.split(" ")
df["도로명(구)"] = address_split.str.get(1)
df

,사업장명,상세영업상태명,지번주소,도로명주소,지번(구),도로명(구)
0,J-PT,영업중,서울특별시 중랑구 묵동 174-29,서울특별시 중랑구 공릉로 18 3층 (묵동),중랑구,중랑구
1,메이크유 필라테스&PT,영업중,서울특별시 구로구 고척동 76-160 골든타워빌딩 4층,서울특별시 구로구 경인로 397 골든타워빌딩 4층 (고척동),구로구,구로구
2,에스짐 양천구청점,영업중,서울특별시 양천구 신정동 294-44,서울특별시 양천구 목동동로8길 15 34층 (신정동),양천구,양천구
3,테디짐PT 서초래미안,영업중,서울특별시 서초구 서초동 1682 서초래미안아파트,서울특별시 서초구 서초대로65길 13-10 2층 207호 (서초동 서초래미안아파트),서초구,서초구
4,플레이스짐,영업중,서울특별시 은평구 역촌동 16-19 니오빌딩,서울특별시 은평구 진흥로 105-6 니오빌딩 2층 (역촌동),은평구,은평구
...,...,...,...,...,...,...
3306,크로스핏 쿠타짐 영등포,영업중,서울특별시 영등포구 양평동3가 77-53 케이타워 지하1층,서울특별시 영등포구 선유동2로 9 케이타워 지하1층 (양평동3가),영등포구,영등포구
3307,크로스핏 긱스,영업중,서울특별시 영등포구 당산동6가 347-6 지하1층,서울특별시 영등포구 양평로12가길 4 지하1층 (당산동6가),영등포구,영등포구
3308,짐구석,영업중,서울특별시 송파구 장지동 881-5 에스비트램스퀘어,서울특별시 송파구 위례광장로 200 에스비트램스퀘어 10층 (장지동),송파구,송파구
3309,와이짐(Y GYM),영업중,서울특별시 강남구 논현동 42-7,서울특별시 강남구 강남대로132길 59 2층 (논현동),강남구,강남구
3310,운동해야짐,영업중,서울특별시 관악구 봉천동 463-3,서울특별시 관악구 양녕로 50 3층 (봉천동),관악구,관악구

In [105]:
# 필요없는 열(주소) 제거
df = df[['사업장명','상세영업상태명','지번(구)','도로명(구)']]
df

              사업장명 상세영업상태명 지번(구) 도로명(구)
0             J-PT     영업중   중랑구    중랑구
1     메이크유 필라테스&PT     영업중   구로구    구로구
2        에스짐 양천구청점     영업중   양천구    양천구
3      테디짐PT 서초래미안     영업중   서초구    서초구
4            플레이스짐     영업중   은평구    은평구
...            ...     ...   ...    ...
3306  크로스핏 쿠타짐 영등포     영업중  영등포구   영등포구
3307       크로스핏 긱스     영업중  영등포구   영등포구
3308           짐구석     영업중   송파구    송파구
3309    와이짐(Y GYM)     영업중   강남구    강남구
3310         운동해야짐     영업중   관악구    관악구

[3311 rows x 4 columns]

In [107]:
# 결손값 NAN 처리
import numpy as np
df.loc[df['지번(구)']=='','지번(구)'] = np.nan
df.loc[df['도로명(구)']=='','도로명(구)'] = np.nan

In [108]:
# 지번 주소가 null인 경우   # 53개
df2 = df[df['지번(구)'].isnull()]
df2

                       사업장명 상세영업상태명 지번(구) 도로명(구)
69                      워너비     영업중   NaN    서초구
113             다이어트모드 휘트니스     영업중   NaN    강북구
227                 (주)바디스타     영업중   NaN     중구
236                  (주)파크짐     영업중   NaN     중구
243              S바디케어프라이빗짐     영업중   NaN     중구
782                    바디어필     영업중   NaN    성북구
810                   에이치 짐     영업중   NaN    성북구
865                    레디포짐     영업중   NaN    강북구
876               피트니스팩토리24     영업중   NaN    강북구
878                    Jfit     영업중   NaN    강북구
890                     제이짐     영업중   NaN    강북구
925                    빌리버짐     영업중   NaN    도봉구
1175           더 짐(The Gym)     영업중   NaN   서대문구
1176                   스퀘어짐     영업중   NaN   서대문구
1177              스타칼리 휘트니스     영업중   NaN   서대문구
1178         247휘트니스 엔 필라테스     영업중   NaN   서대문구
1179             SU FITNESS     영업중   NaN   서대문구
1183               커브스 아현클럽     영업중   NaN   서대문구
1198                 클라우드 짐     영업중   NaN   서대문구
1199                    박스짐     영업중   NaN   서대문구
1201                 M-BASE     영업중   NaN   서대문구
1202                    하이핏     영업중   NaN   서대문구
1706                    에버핏     영업중   NaN    구로구
1708                  바키GYM     영업중   NaN    구로구
1728                크로스핏 잭팟     영업중   NaN    구로구
1730                 엠스트레이닝     영업중   NaN    구로구
1860                    무브짐     영업중   NaN   영등포구
1872                   힙업공장     영업중   NaN   영등포구
1899                    팀닥터     영업중   NaN   영등포구
1997               블루스톤 스포츠     영업중   NaN    동작구
2205                 레몬필라테스     영업중   NaN    서초구
2206                하우스필라테스     영업중   NaN    서초구
2255             얼라인 프라이빗 짐     영업중   NaN    송파구
2267             이루어GYM 서초점     영업중   NaN    서초구
2274              제이짐(Jgym)     영업중   NaN    서초구
2276                   제이주드     영업중   NaN    서초구
2277             진핏 PT 스튜디오     영업중   NaN    서초구
2298          국가대표 소유창 휘트니스     영업중   NaN    서초구
2321              나눔케어 피트니스     영업중   NaN    서초구
2325          참깨체육관 by 짐마일로     영업중   NaN    서초구
2593   PREMIUM 가온태권GYM(481)     영업중   NaN    강남구
2595                   팀제이티     영업중   NaN    강남구
2596                 싸다휘트니스     영업중   NaN    강남구
2597           저스트핏대치점(483)     영업중   NaN    강남구
2603          (주)건강과 땀 휘트니스     영업중   NaN    강남구
2614           FLY GYM 플라이짐     영업중   NaN    강남구
2753            알엑스메소드(375)     영업중   NaN    강남구
2827            탐 프라이빗짐 잠실점     영업중   NaN    송파구
2828           파크하비오휘트니스&골프     영업중   NaN    송파구
2848  Elite training center     영업중   NaN    송파구
2849      (주) 위메이드핏 문정법조타운점     영업중   NaN    송파구
2941                  풍납 헬스     영업중   NaN    송파구
3180                  테디짐PT     영업중   NaN    서초구

In [109]:
# 도로명(구) -> 지역(구)
df2.columns = [['사업장명','상세영업상태명','지번(구)','지역(구)']]
df2 = df2[['사업장명','상세영업상태명','지역(구)']]
df2

                       사업장명 상세영업상태명 지역(구)
69                      워너비     영업중   서초구
113             다이어트모드 휘트니스     영업중   강북구
227                 (주)바디스타     영업중    중구
236                  (주)파크짐     영업중    중구
243              S바디케어프라이빗짐     영업중    중구
782                    바디어필     영업중   성북구
810                   에이치 짐     영업중   성북구
865                    레디포짐     영업중   강북구
876               피트니스팩토리24     영업중   강북구
878                    Jfit     영업중   강북구
890                     제이짐     영업중   강북구
925                    빌리버짐     영업중   도봉구
1175           더 짐(The Gym)     영업중  서대문구
1176                   스퀘어짐     영업중  서대문구
1177              스타칼리 휘트니스     영업중  서대문구
1178         247휘트니스 엔 필라테스     영업중  서대문구
1179             SU FITNESS     영업중  서대문구
1183               커브스 아현클럽     영업중  서대문구
1198                 클라우드 짐     영업중  서대문구
1199                    박스짐     영업중  서대문구
1201                 M-BASE     영업중  서대문구
1202                    하이핏     영업중  서대문구
1706                    에버핏     영업중   구로구
1708                  바키GYM     영업중   구로구
1728                크로스핏 잭팟     영업중   구로구
1730                 엠스트레이닝     영업중   구로구
1860                    무브짐     영업중  영등포구
1872                   힙업공장     영업중  영등포구
1899                    팀닥터     영업중  영등포구
1997               블루스톤 스포츠     영업중   동작구
2205                 레몬필라테스     영업중   서초구
2206                하우스필라테스     영업중   서초구
2255             얼라인 프라이빗 짐     영업중   송파구
2267             이루어GYM 서초점     영업중   서초구
2274              제이짐(Jgym)     영업중   서초구
2276                   제이주드     영업중   서초구
2277             진핏 PT 스튜디오     영업중   서초구
2298          국가대표 소유창 휘트니스     영업중   서초구
2321              나눔케어 피트니스     영업중   서초구
2325          참깨체육관 by 짐마일로     영업중   서초구
2593   PREMIUM 가온태권GYM(481)     영업중   강남구
2595                   팀제이티     영업중   강남구
2596                 싸다휘트니스     영업중   강남구
2597           저스트핏대치점(483)     영업중   강남구
2603          (주)건강과 땀 휘트니스     영업중   강남구
2614           FLY GYM 플라이짐     영업중   강남구
2753            알엑스메소드(375)     영업중   강남구
2827            탐 프라이빗짐 잠실점     영업중   송파구
2828           파크하비오휘트니스&골프     영업중   송파구
2848  Elite training center     영업중   송파구
2849      (주) 위메이드핏 문정법조타운점     영업중   송파구
2941                  풍납 헬스     영업중   송파구
3180                  테디짐PT     영업중   서초구

In [110]:
# 도로명 주소가 null인 경우  # 63개
df3 = df[df['도로명(구)'].isnull()]
df3

               사업장명 상세영업상태명 지번(구) 도로명(구)
165        국제프레야스포츠     영업중    중구    NaN
166        라이온스헬스클럽     영업중    중구    NaN
167    엠.티.엠 휘트니스클럽     영업중    중구    NaN
168      중앙신협휘트니스클럽     영업중    중구    NaN
218        휴레스트웰빙클럽     영업중    중구    NaN
...             ...     ...   ...    ...
1837        에어 스포렉스     영업중  영등포구    NaN
1841            영헬스     영업중  영등포구    NaN
1867  (주)동진카운티스포츠센터     영업중  영등포구    NaN
2172           금성헬스     영업중   서초구    NaN
2269            트리짐     영업중   서초구    NaN

[63 rows x 4 columns]

In [111]:
# 지번(구) -> 지역(구)
df3.columns = [['사업장명','상세영업상태명','지역(구)','도로명(구)']]
df3 = df3[['사업장명','상세영업상태명','지역(구)']]
df3

               사업장명 상세영업상태명 지역(구)
165        국제프레야스포츠     영업중    중구
166        라이온스헬스클럽     영업중    중구
167    엠.티.엠 휘트니스클럽     영업중    중구
168      중앙신협휘트니스클럽     영업중    중구
218        휴레스트웰빙클럽     영업중    중구
...             ...     ...   ...
1837        에어 스포렉스     영업중  영등포구
1841            영헬스     영업중  영등포구
1867  (주)동진카운티스포츠센터     영업중  영등포구
2172           금성헬스     영업중   서초구
2269            트리짐     영업중   서초구

[63 rows x 3 columns]

In [112]:
# 결측값 있는 행 제거   # 3195개
df = df.dropna()
df

              사업장명 상세영업상태명 지번(구) 도로명(구)
0             J-PT     영업중   중랑구    중랑구
1     메이크유 필라테스&PT     영업중   구로구    구로구
2        에스짐 양천구청점     영업중   양천구    양천구
3      테디짐PT 서초래미안     영업중   서초구    서초구
4            플레이스짐     영업중   은평구    은평구
...            ...     ...   ...    ...
3306  크로스핏 쿠타짐 영등포     영업중  영등포구   영등포구
3307       크로스핏 긱스     영업중  영등포구   영등포구
3308           짐구석     영업중   송파구    송파구
3309    와이짐(Y GYM)     영업중   강남구    강남구
3310         운동해야짐     영업중   관악구    관악구

[3195 rows x 4 columns]

In [113]:
# 필요 없는 열 제거
df.columns = [['사업장명','상세영업상태명','지역(구)','도로명(구)']]
df = df[['사업장명','상세영업상태명','지역(구)']]
df

              사업장명 상세영업상태명 지역(구)
0             J-PT     영업중   중랑구
1     메이크유 필라테스&PT     영업중   구로구
2        에스짐 양천구청점     영업중   양천구
3      테디짐PT 서초래미안     영업중   서초구
4            플레이스짐     영업중   은평구
...            ...     ...   ...
3306  크로스핏 쿠타짐 영등포     영업중  영등포구
3307       크로스핏 긱스     영업중  영등포구
3308           짐구석     영업중   송파구
3309    와이짐(Y GYM)     영업중   강남구
3310         운동해야짐     영업중   관악구

[3195 rows x 3 columns]

In [114]:
# df, df2(도로명 주소) 병합
df = pd.concat([df,df2], ignore_index=True)
df

                       사업장명 상세영업상태명 지역(구)
0                      J-PT     영업중   중랑구
1              메이크유 필라테스&PT     영업중   구로구
2                 에스짐 양천구청점     영업중   양천구
3               테디짐PT 서초래미안     영업중   서초구
4                     플레이스짐     영업중   은평구
...                     ...     ...   ...
3243           파크하비오휘트니스&골프     영업중   송파구
3244  Elite training center     영업중   송파구
3245      (주) 위메이드핏 문정법조타운점     영업중   송파구
3246                  풍납 헬스     영업중   송파구
3247                  테디짐PT     영업중   서초구

[3248 rows x 3 columns]

In [115]:
# df, df3(지번 주소) 병합
df = pd.concat([df,df3], ignore_index=True)
df

               사업장명 상세영업상태명 지역(구)
0              J-PT     영업중   중랑구
1      메이크유 필라테스&PT     영업중   구로구
2         에스짐 양천구청점     영업중   양천구
3       테디짐PT 서초래미안     영업중   서초구
4             플레이스짐     영업중   은평구
...             ...     ...   ...
3306        에어 스포렉스     영업중  영등포구
3307            영헬스     영업중  영등포구
3308  (주)동진카운티스포츠센터     영업중  영등포구
3309           금성헬스     영업중   서초구
3310            트리짐     영업중   서초구

[3311 rows x 3 columns]